const configArr = [
  {
    Section: "SignUp",
    Element: "Login",
    type: "REDIRECT",
    target: "",
    Category: "authentication",
    Subcategory: "signup_page",
    Name: "login_button",
    Label: "Login",
  },
  {
    Section: "SignUp",
    Element: "Apply Now\n(Signup Step1)",
    type: "API_CALL",
    target: "/users/pre-signup",
    Category: "authentication",
    Subcategory: "apply_now",
    Name: "auth_signup_step1",
    Label: "Apply Now For Free",
  },
  {
    Section: "SignUp",
    Element: "Confirm OTP\n(Signup Step2)",
    type: "API_CALL",
    target: "/users/signup",
    Category: "authentication",
    Subcategory: "confirm_otp",
    Name: "auth_signup_step2",
    Label: "SIGNUP",
  },
  {
    Section: "SignUp",
    Element: "Resend OTP",
    type: "API_CALL",
    target: "",
    Category: "authentication",
    Subcategory: "resend_otp",
    Name: "auth_signup_step2",
    Label: "Resend",
  },
  {
    Section: "SignUp",
    Element: "Personal Details\n(Signup Step3)",
    type: "API_CALL",
    target: "/users/updateCollegeDetails",
    Category: "authentication",
    Subcategory: "personal_details_fill",
    Name: "auth_signup_step3",
    Label: "Update",
  },
  {
    Section: "SignUp",
    Element: "Set Password\n(Signup Step4)",
    type: "API_CALL",
    target: "/users/set-password",
    Category: "authentication",
    Subcategory: "set_password",
    Name: "auth_signup_step4",
    Label: "Set Password",
  },
  {
    Section: "SignUp",
    Element: "Add Email\n(Signup Step 5)",
    type: "API_CALL",
    target: "/users/sendEmailOTP",
    Category: "authentication",
    Subcategory: "add_email",
    Name: "auth_signup_step5",
    Label: "Send Verification Email",
  },
  {
    Section: "SignUp",
    Element: "Confirm Email OTP\n(Signup Step 6)",
    type: "API_CALL",
    target: "/users/verifyEmailOTP",
    Category: "authentication",
    Subcategory: "confirm_email_otp",
    Name: "auth_signup_step6",
    Label: "Verify Email",
  },

  {
    Section: "Login with Phone",
    Element: "Sign Up",
    type: "REDIRECT",
    target: "",
    Category: "authentication",
    Subcategory: "login_with_phone",
    Name: "signup_button",
    Label: "Sign Up",
  },
  {
    Section: "Login with Phone",
    Element: "Forgot Password",
    type: "REDIRECT",
    target: "",
    Category: "authentication",
    Subcategory: "login_with_phone",
    Name: "forgot_password",
    Label: "Forgot Password",
  },
  {
    Section: "Login with Phone",
    Element: "Login Via Email",
    type: "REDIRECT",
    target: "",
    Category: "authentication",
    Subcategory: "login_with_phone",
    Name: "login_via_email",
    Label: "Login Via Email",
  },
  {
    Section: "Login with Phone",
    Element: "Verify number",
    type: "API_CALL",
    target: "/users/pre-login",
    Category: "authentication",
    Subcategory: "login_with_phone",
    Name: "pre_login",
    Label: "Verify",
  },
  {
    Section: "Login with Phone",
    Element: "Login with Phone",
    type: "API_CALL",
    target: "/users/login",
    Category: "authentication",
    Subcategory: "login_with_phone",
    Name: "login",
    Label: "Login",
  },
  {
    Section: "Login with Phone",
    Element: "Signup",
    type: "API_CALL",
    target: "/users/signup",
    Category: "authentication",
    Subcategory: "confirm_otp",
    Name: "login_signup_step2",
    Label: "SIGNUP",
  },

  {
    Section: "Login with Email",
    Element: "Login",
    type: "API_CALL",
    target: "/users/login-with-email",
    Category: "authentication",
    Subcategory: "login_with_email",
    Name: "login",
    Label: "Login",
  },
  {
    Section: "Login with Email",
    Element: "Login via Phone",
    type: "REDIRECT",
    target: "",
    Category: "authentication",
    Subcategory: "login_with_email",
    Name: "login_with_phone",
    Label: "Login Via Phone",
  },
  {
    Section: "Login with Email",
    Element: "Continue with Google",
    type: "REDIRECT",
    target: "",
    Category: "authentication",
    Subcategory: "login_with_gmail",
    Name: "login",
    Label: "Continue with Google",
  },
  {
    Section: "Login with Email",
    Element: "Sign Up",
    type: "REDIRECT",
    target: "",
    Category: "authentication",
    Subcategory: "login_with_email",
    Name: "signup_button",
    Label: "Sign Up",
  },
  {
    Section: "Login with Email",
    Element: "Forgot Password",
    type: "REDIRECT",
    target: "",
    Category: "authentication",
    Subcategory: "login_with_email",
    Name: "forgot_password",
    Label: "Forgot Password",
  },

  {
    Section: "Redirection",
    Element: "To External",
    type: "REDIRECT",
    target: "",
    Category: "authentication",
    Subcategory: "redirect",
    Name: "external",
    Label: "Redirect to External",
  },
  {
    Section: "Redirection",
    Element: "To Internal",
    type: "REDIRECT",
    target: "",
    Category: "authentication",
    Subcategory: "redirect",
    Name: "internal",
    Label: "Redirect to Internal",
  },
  {
    Section: "Redirection",
    Element: "redirect_uri",
    type: "REDIRECT",
    target: "",
    Category: "authentication",
    Subcategory: "redirect",
    Name: "bos",
    Label: "Redirect to BOS",
  },
  {
    Section: "Redirection",
    Element: "To Auth",
    type: "API_CALL",
    target: "/events/addRegistrantToEvent/{{eventId}}",
    Category: "authentication",
    Subcategory: "redirect",
    Name: "auth_{{eventId}}",
    Label: "Redirect to Auth",
  },

  {
    Section: "Event Registration",
    Element: "Start Learning",
    type: "REDIRECT",
    target: "",
    Category: "authentication",
    Subcategory: "event_registered",
    Name: "start_learning",
    Label: "",
  },
  {
    Section: "Event Registration",
    Element: "Attempt Now",
    type: "REDIRECT",
    target: "",
    Category: "authentication",
    Subcategory: "event_registered",
    Name: "join_event_{{eventId}}",
    Label: "",
  },
];

module.exports = {
  configArr,
};
