const configArr = [
  {
    Page: "Contest Home",
    Section: "All Contests",
    Element: "Select Contest",
    type: "REDIRECT",
    target: "",
    Category: "contest_home",
    Subcategory: "all_contests",
    Name: "select_contest",
    Label: "{{contest}}",
  },
  {
    Page: "Single Contest Home",
    Section: "Single Contest",
    Element: "Start Contest",
    type: "REDIRECT",
    target: "",
    Category: "single_contest",
    Subcategory: "single_contest",
    Name: "start_contest",
    Label: "{{contest}}",
  },
  {
    Page: "Instructions Page",
    Section: "Instructions",
    Element: "Start Test",
    type: "REDIRECT",
    target: "",
    Category: "single_contest",
    Subcategory: "instructions",
    Name: "start_test",
    Label: "{{contest}}",
  },
  {
    Page: "Proctor Page",
    Section: "Proctor Instructions",
    Element: "Start Test",
    type: "REDIRECT",
    target: "",
    Category: "single_contest",
    Subcategory: "proctor_instructions",
    Name: "start_test",
    Label: "{{contest}}",
  },
  {
    Page: "Waiting Page",
    Section: "AutoProctor Video",
    Element: "Video",
    type: "IN_PAGE",
    target: "",
    Category: "single_contest",
    Subcategory: "wait_page",
    Name: "autoproctor_video",
    Label: "Autoproctor Video",
  },
  {
    Page: "Waiting Page",
    Section: "AutoProctor Video",
    Element: "Got It",
    type: "IN_PAGE",
    target: "",
    Category: "single_contest",
    Subcategory: "wait_page",
    Name: "got_it",
    Label: "Got It",
  },
  {
    Page: "Waiting Page",
    Section: "Full Screen Prompt",
    Element: "Go To Full Screen",
    type: "IN_PAGE",
    target: "",
    Category: "single_contest",
    Subcategory: "full_screen_prompt",
    Name: "go_to_fullscreen",
    Label: "Go to Full Screen",
  },
  {
    Page: "Contest All Questions Page",
    Section: "Header",
    Element: "Submit Contest",
    type: "REDIRECT",
    target: "",
    Category: "contest_live",
    Subcategory: "top_navbar",
    Name: "submit_contest",
    Label: "{{contest}}",
  },
  {
    Page: "Contest All Questions Page",
    Section: "Section wise questions",
    Element: "Solve Question",
    type: "REDIRECT",
    target: "",
    Category: "contest_live",
    Subcategory: "all_ques_{{sectionName}}",
    Name: "{{contest}}",
    Label: "attempt_{{question}}",
  },
  {
    Page: "Submission Score",
    Section: "Score Popup",
    Element: "Close Window",
    type: "REDIRECT",
    target: "",
    Category: "contest_live",
    Subcategory: "submitted",
    Name: "{{contest}}",
    Label: "Close Window",
  },
  {
    Page: "Contest IDE",
    Section: "",
    Element: "",
    type: "",
    target: "",
    Category: "",
    Subcategory: "",
    Name: "",
    Label: "",
  },
];

module.exports = {
  configArr,
};
