const configArr = [
  {
    Page: "Common",
    Section: "Floating chat button",
    Element: "Live chat",
    type: "IN_PAGE",
    target: "",
    Category: "maincourse",
    Subcategory: "live_chat",
    Name: "start_chat",
    Label: "",
  },

  {
    Page: "Common",
    Section: "Left Navbar",
    Element: "Home",
    type: "REDIRECT",
    target: "",
    Category: "maincourse",
    Subcategory: "navbar",
    Name: "home",
    Label: "",
  },
  {
    Page: "Common",
    Section: "Left Navbar",
    Element: "Modules",
    type: "",
    target:
      "/course/fetchAssignmentModules\n/course/**moduleId**/questions\n/video/showLectures/**moduleId**",
    Category: "maincourse",
    Subcategory: "navbar",
    Name: "module",
    Label: "",
  },
  {
    Page: "Common",
    Section: "Left Navbar",
    Element: "Live Doubt",
    type: "API_CALL",
    target: "/course/unit/details\n/attachedtags",
    Category: "maincourse",
    Subcategory: "navbar",
    Name: "live_doubt",
    Label: "",
  },
  {
    Page: "Common",
    Section: "Left Navbar",
    Element: "Gym",
    type: "API_CALL",
    target: "/coding-question/all/1",
    Category: "maincourse",
    Subcategory: "navbar",
    Name: "gym",
    Label: "",
  },
  {
    Page: "Common",
    Section: "Left Navbar",
    Element: "Contests",
    type: "API_CALL",
    target: "/contests/all",
    Category: "maincourse",
    Subcategory: "navbar",
    Name: "contests",
    Label: "",
  },
  {
    Page: "Common",
    Section: "Left Navbar",
    Element: "Sessions",
    type: "API_CALL",
    target: "/session/get/{{userId}}/USER",
    Category: "maincourse",
    Subcategory: "navbar",
    Name: "sessions",
    Label: "",
  },
  {
    Page: "Common",
    Section: "Left Navbar",
    Element: "Notes",
    type: "API_CALL",
    target: "/notes/rootLevel",
    Category: "maincourse",
    Subcategory: "navbar",
    Name: "notes",
    Label: "",
  },
  {
    Page: "Common",
    Section: "Left Navbar",
    Element: "open Editor",
    type: "REDIRECT",
    target: "",
    Category: "maincourse",
    Subcategory: "navbar",
    Name: "open_editor",
    Label: "",
  },
  {
    Page: "Common",
    Section: "Left Navbar",
    Element: "Calendar",
    type: "API_CALL",
    target: "/calender/events/{{userId}}/USER",
    Category: "maincourse",
    Subcategory: "navbar",
    Name: "calendar",
    Label: "",
  },
  {
    Page: "Common",
    Section: "Left Navbar",
    Element: "Soft Skills",
    type: "API_CALL",
    target: "/session/get/{{userId}}/USER",
    Category: "maincourse",
    Subcategory: "navbar",
    Name: "soft_skills",
    Label: "",
  },
  {
    Page: "Common",
    Section: "Left Navbar",
    Element: "Projects",
    type: "API_CALL",
    target: "/projects",
    Category: "maincourse",
    Subcategory: "navbar",
    Name: "project",
    Label: "",
  },
  {
    Page: "Common",
    Section: "Left Navbar",
    Element: "Refer & Earn",
    type: "API_CALL",
    target: "/referral/code\n/referral/getReferredUsers",
    Category: "maincourse",
    Subcategory: "navbar",
    Name: "refer_and_earn",
    Label: "",
  },
  {
    Page: "Common",
    Section: "Left Navbar",
    Element: "Job Portal",
    type: "API_CALL",
    target:
      "/job-card/checkJobPortalEligibility\n/student-personal-details/isProfileCompleted\n/job-card/getMockSessionDetails\n/job-card/getJobCardDashBoard\n/job-card/getPlacedStudentsThisMonth\n/job-card/offCampusFeedbackOptions\n/job-card/jobCardValuesMockScorePortal",
    Category: "maincourse",
    Subcategory: "navbar",
    Name: "job_portal",
    Label: "",
  },
  {
    Page: "Common",
    Section: "Left Navbar",
    Element: "Contact BM",
    type: "REDIRECT",
    target: "",
    Category: "maincourse",
    Subcategory: "navbar",
    Name: "contact_bm",
    Label: "",
  },
  {
    Page: "Common",
    Section: "Left Navbar",
    Element: "Profile",
    type: "API_CALL",
    target:
      "/student-personal-details/getGeneralProfileFormFields\n/student-personal-details/leetcode-username",
    Category: "maincourse",
    Subcategory: "navbar",
    Name: "profile",
    Label: "",
  },
  {
    Page: "Common",
    Section: "Left Navbar",
    Element: "Logout",
    type: "REDIRECT",
    target: "",
    Category: "maincourse",
    Subcategory: "navbar",
    Name: "logout",
    Label: "",
  },

  {
    Page: "Homepage",
    Section: "Right pane",
    Element: "Upcoming class",
    type: "REDIRECT",
    target: "",
    Category: "join_class",
    Subcategory: "maincourse_homepage",
    Name: "**class name**",
    Label: "Join Now",
  },
  {
    Page: "Homepage",
    Section: "Right pane",
    Element: "Your Contest",
    type: "REDIRECT",
    target: "",
    Category: "start_contest",
    Subcategory: "maincourse_homepage",
    Name: "**contest name**",
    Label: "Start",
  },
  {
    Page: "Homepage",
    Section: "Right pane",
    Element: "BoS",
    type: "REDIRECT",
    target: "",
    Category: "enter_community",
    Subcategory: "maincourse_homepage",
    Name: "build_on_scenes",
    Label: "Enter Community",
  },
  {
    Page: "Homepage",
    Section: "Latest Module",
    Element: "Start solving module",
    type: "REDIRECT",
    target: "",
    Category: "maincourse_homepage",
    Subcategory: "latest_module",
    Name: "start_solving",
    Label: "Start Solving",
  },
  {
    Page: "Homepage",
    Section: "Job Sincerity",
    Element: "Previous module",
    type: "API_CALL",
    target: "",
    Category: "maincourse_homepage",
    Subcategory: "job_sincerity",
    Name: "previous_module",
    Label: "Previous",
  },
  {
    Page: "Homepage",
    Section: "Job Sincerity",
    Element: "next module",
    type: "API_CALL",
    target: "",
    Category: "maincourse_homepage",
    Subcategory: "job_sincerity",
    Name: "next_module",
    Label: "Next",
  },
  {
    Page: "Homepage",
    Section: "Job Sincerity",
    Element: "know more",
    type: "IN_PAGE",
    target: "",
    Category: "maincourse_homepage",
    Subcategory: "job_sincerity",
    Name: "know_more",
    Label: "Know More",
  },

  {
    Page: "Modules",
    Section: "All courses",
    Element: "Selected course",
    type: "IN_PAGE",
    target: "",
    Category: "maincourse_modules",
    Subcategory: "all_courses",
    Name: "**selected_course**",
    Label: "",
  },
  {
    Page: "Modules",
    Section: "All modules",
    Element: "Selected module",
    type: "API_CALL",
    target: "",
    Category: "maincourse_modules",
    Subcategory: "all_modules",
    Name: "**module name**",
    Label: "",
  },
  {
    Page: "Modules",
    Section: "Selected Module",
    Element: "Join Class",
    type: "REDIRECT",
    target: "",
    Category: "join_class",
    Subcategory: "maincourse_modules",
    Name: "**module name**",
    Label: "",
  },
  {
    Page: "Modules",
    Section: "Selected Module",
    Element: "Assignment",
    type: "IN_PAGE",
    target: "",
    Category: "maincourse_modules",
    Subcategory: "assignments",
    Name: "**module name**",
    Label: "",
  },
  {
    Page: "Modules",
    Section: "Selected Module",
    Element: "Coding Questions",
    type: "REDIRECT",
    target: "",
    Category: "solve_question",
    Subcategory: "maincourse_modules",
    Name: "coding_**questionId**",
    Label: "",
  },
  {
    Page: "Modules",
    Section: "Selected Module",
    Element: "Conceptual Questions",
    type: "REDIRECT",
    target: "",
    Category: "solve_question",
    Subcategory: "maincourse_modules",
    Name: "conceptual_**questionId**",
    Label: "",
  },
  {
    Page: "Modules",
    Section: "Selected Module",
    Element: "Webdev Questions",
    type: "REDIRECT",
    target: "",
    Category: "solve_question",
    Subcategory: "maincourse_modules",
    Name: "webdev_**questionId**",
    Label: "",
  },
  {
    Page: "Modules",
    Section: "Selected Module",
    Element: "Lectures",
    type: "IN_PAGE",
    target: "",
    Category: "maincourse_modules",
    Subcategory: "lectures",
    Name: "**module name**",
    Label: "",
  },
  {
    Page: "Modules",
    Section: "Selected Module",
    Element: "Video player",
    type: "IN_PAGE",
    target: "",
    Category: "watch_recording",
    Subcategory: "maincourse_modules",
    Name: "**video name**",
    Label: "",
  },
  {
    Page: "Modules",
    Section: "Coding Question",
    Element: "",
    type: "",
    target: "",
    Category: "",
    Subcategory: "",
    Name: "",
    Label: "",
  },
  {
    Page: "Modules",
    Section: "Conceptual Question",
    Element: "",
    type: "",
    target: "",
    Category: "",
    Subcategory: "",
    Name: "",
    Label: "",
  },
  {
    Page: "Modules",
    Section: "Github Question",
    Element: "",
    type: "",
    target: "",
    Category: "",
    Subcategory: "",
    Name: "",
    Label: "",
  },

  {
    Page: "Live Doubt",
    Section: "",
    Element: "Select doubt topic dropdown",
    type: "IN_PAGE",
    target: "",
    Category: "maincourse_live_doubt",
    Subcategory: "select_topic",
    Name: "**selected topic**",
    Label: "",
  },
  {
    Page: "Live Doubt",
    Section: "",
    Element: "Type of doubt dropdown",
    type: "IN_PAGE",
    target: "",
    Category: "maincourse_live_doubt",
    Subcategory: "doubt_type",
    Name: "**selected type**",
    Label: "",
  },
  {
    Page: "Live Doubt",
    Section: "",
    Element: "selected time slot",
    type: "IN_PAGE",
    target: "",
    Category: "maincourse_live_doubt",
    Subcategory: "time_slot",
    Name: "**selected slot**",
    Label: "",
  },
  {
    Page: "Live Doubt",
    Section: "",
    Element: "Send Doubt Button",
    type: "API_CALL",
    target: "/livedoubt/adddoubt",
    Category: "maincourse_live_doubt",
    Subcategory: "send_doubt",
    Name: "",
    Label: "",
  },

  {
    Page: "Contests\n\nlive-given\nlive-not-given\npast-given\npast-not-given\nupcoming-given\nupcoming-not-given\nongoing",
    Section: "Top navbar",
    Element: "Live contests",
    type: "IN_PAGE",
    target: "",
    Category: "maincourse_contests",
    Subcategory: "live_contests",
    Name: "",
    Label: "",
  },
  {
    Page: "Contests\n\nlive-given\nlive-not-given\npast-given\npast-not-given\nupcoming-given\nupcoming-not-given\nongoing",
    Section: "Top navbar",
    Element: "Upcoming contests",
    type: "IN_PAGE",
    target: "",
    Category: "maincourse_contests",
    Subcategory: "upcoming_contests",
    Name: "",
    Label: "",
  },
  {
    Page: "Contests\n\nlive-given\nlive-not-given\npast-given\npast-not-given\nupcoming-given\nupcoming-not-given\nongoing",
    Section: "Top navbar",
    Element: "Past contests",
    type: "IN_PAGE",
    target: "",
    Category: "maincourse_contests",
    Subcategory: "past_contests",
    Name: "",
    Label: "",
  },
  {
    Page: "Contests\n\nlive-given\nlive-not-given\npast-given\npast-not-given\nupcoming-given\nupcoming-not-given\nongoing",
    Section: "Live contest",
    Element: "Start contest",
    type: "REDIRECT",
    target: "",
    Category: "start_live_contest",
    Subcategory: "maincourse_contest_live",
    Name: "**contest name**",
    Label: "Start Contest",
  },
  {
    Page: "Contests\n\nlive-given\nlive-not-given\npast-given\npast-not-given\nupcoming-given\nupcoming-not-given\nongoing",
    Section: "Live contest",
    Element: "View Contest",
    type: "REDIRECT",
    target: "",
    Category: "view_live_contest",
    Subcategory: "maincourse_contest_live",
    Name: "**contest name**",
    Label: "View Contest",
  },
  {
    Page: "Contests\n\nlive-given\nlive-not-given\npast-given\npast-not-given\nupcoming-given\nupcoming-not-given\nongoing",
    Section: "Live contest",
    Element: "Resume Contest",
    type: "REDIRECT",
    target: "",
    Category: "view_ongoing_contest",
    Subcategory: "maincourse_contest_live",
    Name: "**contest name**",
    Label: "Resume Contest",
  },
  {
    Page: "Contests\n\nlive-given\nlive-not-given\npast-given\npast-not-given\nupcoming-given\nupcoming-not-given\nongoing",
    Section: "Upcoming contest",
    Element: "View details",
    type: "REDIRECT",
    target: "",
    Category: "view_upcoming_given_contest",
    Subcategory: "maincourse_contest_upcoming",
    Name: "**contest name**",
    Label: "View Details",
  },
  {
    Page: "Contests\n\nlive-given\nlive-not-given\npast-given\npast-not-given\nupcoming-given\nupcoming-not-given\nongoing",
    Section: "Upcoming contest",
    Element: "View details",
    type: "REDIRECT",
    target: "",
    Category: "view_upcoming_not_given_contest",
    Subcategory: "maincourse_contest_upcoming",
    Name: "**contest name**",
    Label: "View Details",
  },
  {
    Page: "Contests\n\nlive-given\nlive-not-given\npast-given\npast-not-given\nupcoming-given\nupcoming-not-given\nongoing",
    Section: "Past contest",
    Element: "View Attempted Contest",
    type: "REDIRECT",
    target: "",
    Category: "view_past_contest_given",
    Subcategory: "maincourse_contest_past",
    Name: "**contest name**",
    Label: "View Contest",
  },
  {
    Page: "Contests\n\nlive-given\nlive-not-given\npast-given\npast-not-given\nupcoming-given\nupcoming-not-given\nongoing",
    Section: "Past contest",
    Element: "View Unattempted Contest",
    type: "REDIRECT",
    target: "",
    Category: "view_past_contest_not_given",
    Subcategory: "maincourse_contest_past",
    Name: "**contest name**",
    Label: "View Contest",
  },
  {
    Page: "Contests\n\nlive-given\nlive-not-given\npast-given\npast-not-given\nupcoming-given\nupcoming-not-given\nongoing",
    Section: "Contest Live Inside Page",
    Element: "Resume Contest",
    type: "REDIRECT",
    target: "",
    Category: "resume_ongoing_contest",
    Subcategory: "maincourse_live_contest",
    Name: "**contest name**",
    Label: "",
  },
  {
    Page: "Contests\n\nlive-given\nlive-not-given\npast-given\npast-not-given\nupcoming-given\nupcoming-not-given\nongoing",
    Section: "Contest Live Inside Page",
    Element: "Start Contest",
    type: "REDIRECT",
    target: "",
    Category: "start_live_contest",
    Subcategory: "maincourse_live_contest",
    Name: "**contest name**",
    Label: "",
  },
  {
    Page: "Contests\n\nlive-given\nlive-not-given\npast-given\npast-not-given\nupcoming-given\nupcoming-not-given\nongoing",
    Section: "Contest Upcoming Inside Page",
    Element: "",
    type: "",
    target: "",
    Category: "",
    Subcategory: "",
    Name: "",
    Label: "",
  },
  {
    Page: "Contests\n\nlive-given\nlive-not-given\npast-given\npast-not-given\nupcoming-given\nupcoming-not-given\nongoing",
    Section: "Contest Past Inside Page",
    Element: "Start Question",
    type: "REDIRECT",
    target: "",
    Category: "solve_question",
    Subcategory: "maincourse_past_contest",
    Name: "contest_attempted_**question**",
    Label: "Start Question",
  },
  {
    Page: "Contests\n\nlive-given\nlive-not-given\npast-given\npast-not-given\nupcoming-given\nupcoming-not-given\nongoing",
    Section: "Contest Past Inside Page",
    Element: "View Attempted Question",
    type: "REDIRECT",
    target: "",
    Category: "solve_question",
    Subcategory: "maincourse_past_contest",
    Name: "contest_unattempted_**question**",
    Label: "Solved",
  },

  {
    Page: "Session",
    Section: "Suggested Session box",
    Element: "Book Session",
    type: "API_CALL",
    target: "/session/getAvailaibleSlots",
    Category: "book_session",
    Subcategory: "maincourse_session_suggested",
    Name: "**sessionId**",
    Label: "Book Session",
  },
  {
    Page: "Session",
    Section: "Book session modal",
    Element: "Pick your slot",
    type: "API_CALL",
    target: "/session/bookSessionWithMentor",
    Category: "select_slot_session",
    Subcategory: "maincourse_session_book_modal",
    Name: "**sessionId**",
    Label: "**Time Slot**",
  },
  {
    Page: "Session",
    Section: "Active Session",
    Element: "Raise a Request (visible when scheduled)",
    type: "IN_PAGE",
    target: "",
    Category: "raise_session_request",
    Subcategory: "maincourse_session_active_session",
    Name: "**sessionId**",
    Label: "",
  },
  {
    Page: "Session",
    Section: "Active Session",
    Element: "Show Report Card",
    type: "IN_PAGE",
    target: "",
    Category: "show_report_card",
    Subcategory: "maincourse_session",
    Name: "**sessionId**",
    Label: "",
  },
  {
    Page: "Session",
    Section: "Active Session",
    Element: "Book Session",
    type: "API_CALL",
    target: "/session/getAvailaibleSlots",
    Category: "book_session",
    Subcategory: "maincourse_session_active_session",
    Name: "**sessionId**",
    Label: "",
  },
  {
    Page: "Session",
    Section: "Cancel",
    Element: "Cancel Interview",
    type: "IN_PAGE",
    target: "",
    Category: "cancel_session",
    Subcategory: "maincourse_session_active_session",
    Name: "**sessionId & s.id**",
    Label: "",
  },
  {
    Page: "Session",
    Section: "Cancel",
    Element: "Yes I want to cancel my interview",
    type: "API_CALL",
    target: "session/cancel",
    Category: "cancel_session_confirm",
    Subcategory: "maincourse_session_cancel_modal",
    Name: "**sessionId & s.id**",
    Label: "",
  },
  {
    Page: "Session",
    Section: "Cancel",
    Element: "No",
    type: "IN_PAGE",
    target: "",
    Category: "cancel_session_cancel",
    Subcategory: "maincourse_session_cancel_modal",
    Name: "**sessionId & s.id**",
    Label: "",
  },
  {
    Page: "Session",
    Section: "Reschedule",
    Element: "Reschedule Session",
    type: "API_CALL",
    target: "/session/getAvailaibleSlots",
    Category: "reschedule_session",
    Subcategory: "maincourse_session",
    Name: "**sessionId & s.id**",
    Label: "",
  },
  {
    Page: "Session",
    Section: "Other Sessions",
    Element: "Raise a Request",
    type: "IN_PAGE",
    target: "",
    Category: "raise_session_request",
    Subcategory: "maincourse_session_active_session",
    Name: "**sessionId**",
    Label: "",
  },
  {
    Page: "Session",
    Section: "Other Sessions",
    Element: "Show Report Card",
    type: "IN_PAGE",
    target: "",
    Category: "show_report_card",
    Subcategory: "maincourse_session",
    Name: "**sessionId**",
    Label: "",
  },
  {
    Page: "Session",
    Section: "Other Sessions",
    Element: "Fill feedback (on top of card)",
    type: "REDIRECT",
    target: "",
    Category: "fill_feedback",
    Subcategory: "maincourse_session",
    Name: "**sessionId & s.id**",
    Label: "",
  },
  {
    Page: "Session",
    Section: "Other Sessions",
    Element: "Fill feedback (inside card)",
    type: "REDIRECT",
    target: "",
    Category: "fill_feedback",
    Subcategory: "maincourse_session",
    Name: "**sessionId & s.id**",
    Label: "",
  },
  {
    Page: "Session",
    Section: "Other Sessions",
    Element: "View Feedback",
    type: "IN_PAGE",
    target: "",
    Category: "view_feedback",
    Subcategory: "maincourse_session",
    Name: "**sessionId & s.id**",
    Label: "",
  },
  {
    Page: "Session",
    Section: "Other Sessions",
    Element: "View Recording",
    type: "IN_PAGE",
    target: "",
    Category: "view_session_recording",
    Subcategory: "maincourse_session",
    Name: "**sessionId & s.id**",
    Label: "",
  },
  {
    Page: "Session",
    Section: "Detailed Feedback Modal",
    Element: "Show Feedback",
    type: "IN_PAGE",
    target: "",
    Category: "view_detailed_feedback",
    Subcategory: "maincourse_session_feedback_modal",
    Name: "**sessionId & s.id**",
    Label: "",
  },
  {
    Page: "Session",
    Section: "Raise Request Modal",
    Element: "Yes send request",
    type: "API_CALL",
    target:
      "session/eligibility/raiseRequestForSessionEligibilty/**sessionId**",
    Category: "raise_session_request_confirm",
    Subcategory: "maincourse_session_request_modal",
    Name: "**sessionId**",
    Label: "",
  },
  {
    Page: "Session",
    Section: "Raise Request Modal",
    Element: "No dont raise",
    type: "IN_PAGE",
    target: "",
    Category: "raise_session_request_cancel",
    Subcategory: "maincourse_session_request_modal",
    Name: "**sessionId**",
    Label: "",
  },

  {
    Page: "Notes",
    Section: "Topic/Subtopic clicked",
    Element: "Topic/Subtopic",
    type: "IN_PAGE",
    target: "",
    Category: "view_notes",
    Subcategory: "maincourse_notes",
    Name: "**topic/subtopic name**",
    Label: "",
  },

  {
    Page: "Open Editor",
    Section: "IDE",
    Element: "Coding Language",
    type: "IN_PAGE",
    target: "",
    Category: "maincourse_open_editor",
    Subcategory: "coding_language",
    Name: "open_editor",
    Label: "",
  },
  {
    Page: "Notes",
    Section: "",
    Element: "Reset code",
    type: "IN_PAGE",
    target: "",
    Category: "maincourse_open_editor",
    Subcategory: "reset_code",
    Name: "open_editor",
    Label: "",
  },
  {
    Page: "Notes",
    Section: "",
    Element: "Settings",
    type: "IN_PAGE",
    target: "",
    Category: "maincourse_open_editor",
    Subcategory: "settings",
    Name: "open_editor",
    Label: "",
  },
  {
    Page: "Notes",
    Section: "",
    Element: "Full screen",
    type: "IN_PAGE",
    target: "",
    Category: "maincourse_open_editor",
    Subcategory: "full_screen",
    Name: "open_editor",
    Label: "",
  },
  {
    Page: "Notes",
    Section: "",
    Element: "Get Expected Output",
    type: "API_CALL",
    target: "coding-question/getExpectedOutput",
    Category: "maincourse_open_editor",
    Subcategory: "get_expected_output",
    Name: "open_editor",
    Label: "",
  },
  {
    Page: "Notes",
    Section: "",
    Element: "Run your code",
    type: "API_CALL",
    target: "coding-question/runTestCase",
    Category: "maincourse_open_editor",
    Subcategory: "run_your_code",
    Name: "open_editor",
    Label: "",
  },
  {
    Page: "Notes",
    Section: "",
    Element: "Console",
    type: "IN_PAGE",
    target: "",
    Category: "maincourse_open_editor",
    Subcategory: "console",
    Name: "open_editor",
    Label: "",
  },
  {
    Page: "Notes",
    Section: "",
    Element: "Submit",
    type: "API_CALL",
    target: "judge0/submission",
    Category: "maincourse_open_editor",
    Subcategory: "submit_question",
    Name: "open_editor",
    Label: "",
  },

  {
    Page: "Calendar?",
    Section: "",
    Element: "",
    type: "",
    target: "",
    Category: "",
    Subcategory: "",
    Name: "",
    Label: "",
  },

  {
    Page: "Soft Skills",
    Section: "Right Pane",
    Element: "Book Resume Mock",
    type: "REDIRECT",
    target: "",
    Category: "book_session",
    Subcategory: "maincourse",
    Name: "soft_skills",
    Label: "",
  },
  {
    Page: "Soft Skills",
    Section: "Right Pane",
    Element: "",
    type: "IN_PAGE",
    target: "",
    Category: "raise_session_request_confirm",
    Subcategory: "maincourse",
    Name: "soft_skills",
    Label: "",
  },
  {
    Page: "Soft Skills",
    Section: "Right Pane",
    Element: "Solve Aptitude Handbook",
    type: "REDIRECT",
    target: "",
    Category: "maincourse",
    Subcategory: "soft_skills",
    Name: "aptitude_handbook",
    Label: "",
  },
  {
    Page: "Soft Skills",
    Section: "Right Pane",
    Element: "Join Discord",
    type: "REDIRECT",
    target: "",
    Category: "maincourse",
    Subcategory: "soft_skills",
    Name: "join_discord",
    Label: "",
  },
  {
    Page: "Soft Skills",
    Section: "Right Pane",
    Element: "Check Ideal LinkedIn Profile",
    type: "REDIRECT",
    target: "",
    Category: "maincourse",
    Subcategory: "soft_skills",
    Name: "ideal_linkedin_profile",
    Label: "",
  },
  {
    Page: "Soft Skills",
    Section: "Right Pane",
    Element: "Check Ideal Resume",
    type: "REDIRECT",
    target: "",
    Category: "maincourse",
    Subcategory: "soft_skills",
    Name: "ideal_resume",
    Label: "",
  },
  {
    Page: "Soft Skills",
    Section: "Book Resume Mock Modal",
    Element: "Contact BM",
    type: "API_CALL",
    target:
      "session/eligibility/raiseRequestForSessionEligibilty/**sessionId**",
    Category: "raise_session_request_confirm",
    Subcategory: "maincourse",
    Name: "soft_skills",
    Label: "",
  },
  {
    Page: "Soft Skills",
    Section: "Cards",
    Element: "Start Practicing HR Questions",
    type: "REDIRECT",
    target: "",
    Category: "maincourse",
    Subcategory: "soft_skills",
    Name: "practice_hr_questions",
    Label: "",
  },
  {
    Page: "Soft Skills",
    Section: "Cards",
    Element: "Check Interview Etiquettes",
    type: "REDIRECT",
    target: "",
    Category: "maincourse",
    Subcategory: "soft_skills",
    Name: "interview_etiquettes",
    Label: "",
  },
  {
    Page: "Soft Skills",
    Section: "Cards",
    Element: "Check what to do before interview",
    type: "REDIRECT",
    target: "",
    Category: "maincourse",
    Subcategory: "soft_skills",
    Name: "preprepared_for_interview",
    Label: "",
  },
  {
    Page: "Soft Skills",
    Section: "Cards",
    Element: "learn to write cold emails",
    type: "REDIRECT",
    target: "",
    Category: "maincourse",
    Subcategory: "soft_skills",
    Name: "cold_emails",
    Label: "",
  },
  {
    Page: "Soft Skills",
    Section: "Cards",
    Element: "learn personality skills",
    type: "REDIRECT",
    target: "",
    Category: "maincourse",
    Subcategory: "soft_skills",
    Name: "personality_skills",
    Label: "",
  },

  {
    Page: "Projects",
    Section: "Resources to help",
    Element: "Video(s)",
    type: "IN_PAGE",
    target: "",
    Category: "maincourse_projects",
    Subcategory: "video_clicked",
    Name: "**video name**",
    Label: "",
  },
  {
    Page: "Projects",
    Section: "Video Modal",
    Element: "Video name",
    type: "IN_PAGE",
    target: "",
    Category: "maincourse_projects",
    Subcategory: "video_selected",
    Name: "**video name**",
    Label: "",
  },
  {
    Page: "Projects",
    Section: "Video Modal",
    Element: "Video started",
    type: "IN_PAGE",
    target: "",
    Category: "maincourse_projects",
    Subcategory: "video_started",
    Name: "**video name**",
    Label: "",
  },
  {
    Page: "Projects",
    Section: "Projects for you",
    Element: "Start a Project",
    type: "REDIRECT",
    target: "",
    Category: "maincourse_projects",
    Subcategory: "start_project",
    Name: "**project name/id**",
    Label: "",
  },

  {
    Page: "Single Project Page",
    Section: "Project Step",
    Element: "Mark as Done",
    type: "API_CALL",
    target: "projects/mark-step-done",
    Category: "maincourse_projects",
    Subcategory: "mark_step_as_done",
    Name: "**projectId + stepId/number (need to see if step is the last one/check if its final submission)**",
    Label:
      "Do we need to see if user is opening new, unfinished or completed project from frontend?",
  },
  {
    Page: "Single Project Page",
    Section: "Project Step",
    Element: "Go to Previous Step",
    type: "IN_PAGE",
    target: "",
    Category: "maincourse_projects",
    Subcategory: "go_previous_step",
    Name: "**projectId + stepId**",
    Label: "",
  },
  {
    Page: "Single Project Page",
    Section: "Project Step",
    Element: "Go to Next",
    type: "IN_PAGE",
    target: "",
    Category: "maincourse_projects",
    Subcategory: "go_next_step",
    Name: "**projectId + stepId**",
    Label: "",
  },
  {
    Page: "Single Project Page",
    Section: "Steps panel",
    Element: "Step clicked",
    type: "IN_PAGE",
    target: "",
    Category: "maincourse_projects",
    Subcategory: "steps_panel_step",
    Name: "**projectId + stepId**",
    Label: "",
  },

  {
    Page: "Refer and earn",
    Section: "top cards",
    Element: "Earned Cash",
    type: "IN_PAGE",
    target: "",
    Category: "maincourse",
    Subcategory: "refer_and_earn",
    Name: "earned_cash",
    Label: "Know More",
  },
  {
    Page: "Refer and earn",
    Section: "top cards",
    Element: "Your Referral",
    type: "IN_PAGE",
    target: "",
    Category: "maincourse",
    Subcategory: "refer_and_earn",
    Name: "your_referral",
    Label: "Know More",
  },
  {
    Page: "Refer and earn",
    Section: "top cards",
    Element: "Potential Earnings",
    type: "IN_PAGE",
    target: "",
    Category: "maincourse",
    Subcategory: "refer_and_earn",
    Name: "potential_earnings",
    Label: "Know More",
  },
  {
    Page: "Refer and earn",
    Section: "Share with friends",
    Element: "Copy Ref Link",
    type: "IN_PAGE",
    target: "",
    Category: "maincourse",
    Subcategory: "refer_and_earn",
    Name: "copy_ref_link",
    Label: "Copy Link",
  },
  {
    Page: "Refer and earn",
    Section: "Share with friends",
    Element: "WhatsApp",
    type: "IN_PAGE",
    target: "",
    Category: "maincourse",
    Subcategory: "refer_and_earn",
    Name: "share_whatsapp",
    Label: "WhatsApp icon",
  },
  {
    Page: "Refer and earn",
    Section: "Refer your friend",
    Element: "Submit friend details",
    type: "API_CALL",
    target: "referral/potential-referral",
    Category: "maincourse",
    Subcategory: "refer_and_earn",
    Name: "submit_referral",
    Label: "Submit",
  },
  {
    Page: "Refer and earn",
    Section: "FAQs",
    Element: "",
    type: "",
    target: "",
    Category: "",
    Subcategory: "",
    Name: "",
    Label: "",
  },
  {
    Page: "Refer and earn",
    Section: "Footer",
    Element: "Contact Us",
    type: "REDIRECT",
    target: "",
    Category: "maincourse",
    Subcategory: "refer_and_earn",
    Name: "contact_us",
    Label: "Contact us",
  },

  {
    Page: "Job Portal",
    Section: "Top navbar",
    Element: "Jobs For You",
    type: "IN_PAGE",
    target: "",
    Category: "job_portal",
    Subcategory: "top_navbar",
    Name: "jobs_for_you",
    Label: "",
  },
  {
    Page: "Job Portal",
    Section: "Top navbar",
    Element: "Explore Job Drives",
    type: "IN_PAGE",
    target: "",
    Category: "job_portal",
    Subcategory: "top_navbar",
    Name: "explore_job_drives",
    Label: "",
  },
  {
    Page: "Job Portal",
    Section: "Top navbar",
    Element: "Your Applications",
    type: "API_CALL",
    target: "/job-card/jobCardValuesAppliedMainPortal",
    Category: "job_portal",
    Subcategory: "top_navbar",
    Name: "your_applications",
    Label: "",
  },
  {
    Page: "Job Portal",
    Section: "Top navbar",
    Element: "Off Campus",
    type: "API_CALL",
    target:
      "/job-card/multiSelectValuesjobCardOffCampus\n/job-card/offCampusCardsWithFilters",
    Category: "job_portal",
    Subcategory: "top_navbar",
    Name: "off_campus",
    Label: "",
  },
  {
    Page: "Job Portal",
    Section: "Jobs for you Selected",
    Element: "Apply Now",
    type: "API_CALL",
    target: "job-card/getJobCardCompanyFromJobCardId?jobCardId=**jobCardId**",
    Category: "apply_for_job_card",
    Subcategory: "job_portal_jobs_for_you",
    Name: "**jobCardId**",
    Label: "Apply Now",
  },
  {
    Page: "Job Portal",
    Section: "Jobs for you Selected",
    Element: "More Details",
    type: "API_CALL",
    target: "job-card/getJobCardDetails?jobCardId=**cardId**",
    Category: "view_drive_details",
    Subcategory: "job_portal_jobs_for_you",
    Name: "**jobCardId**",
    Label: "More Details",
  },
  {
    Page: "Job Portal",
    Section: "Apply Now Modal",
    Element: "Apply Now",
    type: "API_CALL",
    target: "job-card/applyJobCard",
    Category: "final_apply_for_job_card",
    Subcategory: "job_portal_jobs_for_you",
    Name: "**jobCardId**",
    Label: "Apply Now",
  },
  {
    Page: "Job Portal",
    Section: "More Details Modal",
    Element: "Resource Link",
    type: "REDIRECT",
    target: "",
    Category: "resource_link",
    Subcategory: "job_portal_more_details",
    Name: "**jobCardId**",
    Label: "",
  },
  {
    Page: "Job Portal",
    Section: "More Details Modal",
    Element: "Apply Now",
    type: "API_CALL",
    target: "job-card/getJobCardCompanyFromJobCardId?jobCardId=**jobCardId**",
    Category: "apply_for_job_card",
    Subcategory: "job_portal_more_details",
    Name: "**jobCardId**",
    Label: "Apply Now",
  },
  {
    Page: "Job Portal",
    Section: "ANSHUL (different for explore JD?)",
    Element: "",
    type: "",
    target: "",
    Category: "",
    Subcategory: "",
    Name: "",
    Label: "",
  },
  {
    Page: "Job Portal",
    Section: "Your Applications",
    Element: "More Details",
    type: "API_CALL",
    target: "job-card/getJobCardDetails?jobCardId=**cardId**",
    Category: "view_drive_details",
    Subcategory: "job_portal_your_applications",
    Name: "**jobCardId**",
    Label: "",
  },
  {
    Page: "Job Portal",
    Section: "More Details Modal",
    Element: "Resource Link",
    type: "REDIRECT",
    target: "",
    Category: "resource_link",
    Subcategory: "job_portal_more_details",
    Name: "**jobCardId**",
    Label: "",
  },
  {
    Page: "Job Portal",
    Section: "OffCampus",
    Element: "Apply",
    type: "REDIRECT",
    target: "",
    Category: "apply_for_off_campus",
    Subcategory: "job_portal_off_campus",
    Name: "**offcampus jobcard id**",
    Label: "",
  },
  {
    Page: "Job Portal",
    Section: "OffCampus",
    Element: "Update Status",
    type: "API_CALL",
    target: "/job-card/feedbackOffCampus",
    Category: "update_status_off_campus",
    Subcategory: "job_portal_off_campus",
    Name: "**offcampus jobcard id**",
    Label: "",
  },
  {
    Page: "Job Portal",
    Section: "Right Pane",
    Element: "Share Job Opportunity",
    type: "REDIRECT",
    target: "",
    Category: "job_portal",
    Subcategory: "right_pane",
    Name: "share_job_opportunity",
    Label: "",
  },
  {
    Page: "Job Portal",
    Section: "Right Pane",
    Element: "Last Mock Sore",
    type: "API_CALL",
    target: "/users/userMockScores",
    Category: "job_portal",
    Subcategory: "right_pane",
    Name: "view_mock_scores",
    Label: "",
  },
  {
    Page: "Job Portal",
    Section: "Right Pane",
    Element: "Dashboard: Eligible",
    type: "IN_PAGE",
    target: "",
    Category: "job_portal",
    Subcategory: "right_pane_dashboard",
    Name: "eligible",
    Label: "",
  },
  {
    Page: "Job Portal",
    Section: "Right Pane",
    Element: "Dashboard: NotApplied",
    type: "IN_PAGE",
    target: "",
    Category: "job_portal",
    Subcategory: "right_pane_dashboard",
    Name: "not_applied",
    Label: "",
  },
  {
    Page: "Job Portal",
    Section: "Right Pane",
    Element: "Dashboard: Applied",
    type: "IN_PAGE",
    target: "",
    Category: "job_portal",
    Subcategory: "right_pane_dashboard",
    Name: "applied",
    Label: "",
  },
  {
    Page: "Job Portal",
    Section: "Right Pane",
    Element: "Dashboard: Ongoing Tests",
    type: "IN_PAGE",
    target: "",
    Category: "job_portal",
    Subcategory: "right_pane_dashboard",
    Name: "ongoing_online_tests",
    Label: "",
  },
  {
    Page: "Job Portal",
    Section: "Right Pane",
    Element: "Dashboard: going Tech Interviews",
    type: "IN_PAGE",
    target: "",
    Category: "job_portal",
    Subcategory: "right_pane_dashboard",
    Name: "ongoing_technical_interviews",
    Label: "",
  },
  {
    Page: "Job Portal",
    Section: "Right Pane",
    Element: "Dashboard: Ongoing HR",
    type: "IN_PAGE",
    target: "",
    Category: "job_portal",
    Subcategory: "right_pane_dashboard",
    Name: "ongoing_hr_rounds",
    Label: "",
  },
  {
    Page: "Job Portal",
    Section: "Right Pane",
    Element: "Dashboard: Rejected in Tests",
    type: "IN_PAGE",
    target: "",
    Category: "job_portal",
    Subcategory: "right_pane_dashboard",
    Name: "rejected_in_tests",
    Label: "",
  },
  {
    Page: "Job Portal",
    Section: "Right Pane",
    Element: "Dashboard: Rejected in Interviews",
    type: "IN_PAGE",
    target: "",
    Category: "job_portal",
    Subcategory: "right_pane_dashboard",
    Name: "rejected_in_interviews",
    Label: "",
  },
  {
    Page: "Job Portal",
    Section: "Right Pane",
    Element: "Dashboard: Rejected in HR",
    type: "IN_PAGE",
    target: "",
    Category: "job_portal",
    Subcategory: "right_pane_dashboard",
    Name: "rejected_in_hr_rounds",
    Label: "",
  },

  {
    Page: "Coding Question",
    Section: "Right Pane",
    Element: "",
    type: "",
    target: "",
    Category: "",
    Subcategory: "",
    Name: "",
    Label: "",
  },
  {
    Page: "Conceptual Question",
    Section: "Right Pane",
    Element: "",
    type: "",
    target: "",
    Category: "",
    Subcategory: "",
    Name: "",
    Label: "",
  },
  {
    Page: "Webdev Question",
    Section: "Right Pane",
    Element: "",
    type: "",
    target: "",
    Category: "",
    Subcategory: "",
    Name: "",
    Label: "",
  },

  {
    Page: "Gym",
    Section: "Right Pane",
    Element: "",
    type: "",
    target: "",
    Category: "",
    Subcategory: "",
    Name: "",
    Label: "",
  },
];

module.exports = {
  configArr,
};
